### ISSUE TITLE
Modals for Create byte, share byte, bookmark byte needs to be corrected for button position and content height

### ISSUE THREAD

**Issue by bidyut-majumdar** [manojnegi07/social-external#1061]
![5](https://github.com/manojnegi07/social-external/assets/78781245/77a45d82-a6eb-4ba7-8da7-758a0a94942b)
![6](https://github.com/manojnegi07/social-external/assets/78781245/32ef037d-d0d1-4a5c-bb01-9ab69aeba034)
![7](https://github.com/manojnegi07/social-external/assets/78781245/af7e1c97-2e0e-4c0a-ba1e-8738b0535f05)

**Comment by bidyut-majumdar** [comment]
This was mobile view.

1. The buttons (share, byte, bookmark) were appearing at center of the screen (not at bottom) causing huge space at both up & down side.
2. if it's on bottomsheet approach then the height of the modal to be from bottom to top, but the content parts are at top here, so after message container its having empty area at bottom side .

**Comment by vayuzpriya** [comment]
@bidyut-majumdar This is intesnally done. Can't fix all button in bottom because if i fixed button in bottom then too much space looks in middle section and forasmuch this is not app so if we fix the botton on bottom then it's visible half then we scroll up then it's visible full because of address bar on brower
